[placeholders]
name = {type="string", prompt="Screen name?", default="screen"}
assets = {type="bool", prompt="Require assets?" }
strategy = {type="string", prompt="Loading strategy?", choices=["Blocking", "NonBlocking"] }
