# ------------------------------------------
# SPDX-License-Identifier: MIT OR Apache-2.0
# -------------------------------- ğ’’ğ’‘ğ’“ğ’ğ’‹ --
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# Linux builds
[target.nightly-x86_64-unknown-linux-gnu]
linker = "mold"
rustflags = [
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
]
